name: Deploy Website

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Copy files to remote server
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
        run: |
          mkdir ~/.ssh
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
          chmod 0600 ~/.ssh/known_hosts
          sshpass -p "$SSH_PASSWORD" rsync -az ./* "$SSH_USER@$SSH_HOST:/home/$SSH_USER/new_website/"
      - name: SSH into host
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -t "$SSH_USER@$SSH_HOST" <<'EOF'
          rm -r website
          mv new_website website
          mkdir new_website
          cp .env new_website/
          cd website
          php8.2 -c ~/etc/php8.2 /usr/bin/composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
          npm i --silent --no-progress
          npm run build
          php8.2 -c ~/etc/php8.2 artisan key:generate --force
          php8.2 -c ~/etc/php8.2 artisan storage:link -n --force
          php8.2 -c ~/etc/php8.2 artisan migrate:fresh -n --force
          php8.2 -c ~/etc/php8.2 artisan db:seed -n --force
          EOF
