name: Test Laravel

on:
  pull_request:
    branches: [ "master" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-24.04

    steps:
      - uses: shivammathur/setup-php@7f1cfc01ecf2c1017bd451f44306c248496838e2
        with:
          php-version: '8.3'
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4.1.0
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
        run: |
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
          npm i --silent --no-progress
          npm run build
      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Create Database
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: |
          touch database/database.sqlite
          php artisan migrate -n
          php artisan db:seed -n
      - name: Execute tests via PHPUnit/Pest and run application
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/testing.sqlite
        run: |
          touch database/test.sqlite
          php artisan test
          php artisan serve &
          kill %1
